"""Inicijalna migracija

Revision ID: 66d8113663ac
Revises: 
Create Date: 2024-01-24 19:43:28.623108

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66d8113663ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('statusID', sa.Integer(), nullable=False),
    sa.Column('buyer', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['statusID'], ['statuses.statusID'], ),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('productCategories',
    sa.Column('productCategoryId', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.Column('categoryID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categoryID'], ['categories.categoryID'], ),
    sa.ForeignKeyConstraint(['productID'], ['products.productID'], ),
    sa.PrimaryKeyConstraint('productCategoryId')
    )
    op.create_table('productQuantities',
    sa.Column('productQuantityID', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['orderID'], ['orders.orderID'], ),
    sa.ForeignKeyConstraint(['productID'], ['products.productID'], ),
    sa.PrimaryKeyConstraint('productQuantityID')
    )
    op.alter_column('statuses', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('statuses', 'name',
               existing_type=mysql.VARCHAR(length=256),
               nullable=True)
    op.drop_table('productQuantities')
    op.drop_table('productCategories')
    op.drop_table('orders')
    # ### end Alembic commands ###
