"""Inicijalna migracija

Revision ID: 1ded490a45c2
Revises: 
Create Date: 2024-01-20 02:55:29.954974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ded490a45c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Role')
    op.drop_table('UserRole')
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('UserRole',
    sa.Column('UserRole', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('roleID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('UserRole'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Role',
    sa.Column('roleID', mysql.MEDIUMINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('roleID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
